### ISSUE TITLE
how to keep/load .vimrc style configuration?

### ISSUE THREAD

**Issue by sevaivanov** [tidalcycles/vim-tidal#17]
e.g. visual line is not highlighting but I do have it properly configured in my .vimrc

perhaps, i missed some documentation? however :colorscheme evening etc. works~!

cheers,
seva

**Comment by munshkr** [comment]
Late reply, and I guess you solved it or at least is not an issue anymore, but I'll clarify for others, just in case. The plugin does not add any syntax highlighting settings on its own, it relies on Vim's default for Haskell files (or some other ones if you have a Haskell-related plugin).
