### ISSUE TITLE
"#" red highlighting

### ISSUE THREAD

**Issue by ovitus** [tidalcycles/vim-tidal#24]
Why is it that the hash symbol (#) causes the line to be highlighted red? This only happens with .tidal files.
![red](https://user-images.githubusercontent.com/44982087/48964531-82d5da80-ef77-11e8-8518-515d8bd75846.png)

**Comment by munshkr** [comment]
I've seen this before. Apparently, the default syntax highlighting that Vim provides for Haskell files does not like lines starting with the `#` operator (even if its valid Haskell in this case). As a workaround, you can try installing [this third party plugin for Haskell](https://github.com/neovimhaskell/haskell-vim). If you're using Plug, add this to your `.vimrc` (in your plugins section):

```
Plug 'neovimhaskell/haskell-vim'
```

Then restart Vim and call `:PlugInstall`.

I'll keep this issue open so I can figure out what's causing it and patch it here.

**Comment by munshkr** [comment]
I've fixed this by including the haskell syntax file as "tidal" syntax file. Also fixed how it highlighted new lines starting with a `#`, as they were highlighted as Haskell preprocessing macros:

![screenshot_2018-11-24_09-51-35](https://user-images.githubusercontent.com/4862/48968436-9ceed780-efce-11e8-8184-61d382aa3f6b.png)

You can just upgrade the plugin with `:PlugUpdate` to get the latest fix.

**Comment by ovitus** [comment]
I updated, highlights are gone, but nothing works when I use the hash below the primary pattern, it has no effect. For instance:

d1 $ n "[-3 6 1] 4" # s "midi" # sustain "0.1"

will sustain notes 0.1

d1 $ n "[-3 6 1] 4" # s "midi"
# sustain "0.1"

sustain ignored
