### ISSUE TITLE
hash issue

### ISSUE THREAD

**Issue by ovitus** [tidalcycles/vim-tidal#25]
![screenshot_2018-11-24_09-51-35](https://user-images.githubusercontent.com/4862/48968436-9ceed780-efce-11e8-8184-61d382aa3f6b.png)

You can just upgrade the plugin with `:PlugUpdate` to get the latest fix.

_Originally posted by @munshkr in https://github.com/tidalcycles/vim-tidal/issues/24#issuecomment-441365873_

I updated, highlights are gone, but nothing works when I use the hash below the primary pattern, it has no effect. For instance:

```
d1 $ n "[-3 6 1] 4" # s "midi" # sustain "0.1"

will sustain notes 0.1

d1 $ n "[-3 6 1] 4" # s "midi"
# sustain "0.1"

sustain ignored
```

**Comment by munshkr** [comment]
Oops. Sorry, you're right, I broke something. Try updating again.
