### ISSUE TITLE
Transitions are with their parameters switched

### ISSUE THREAD

**Issue by gilfuser** [tidalcycles/vim-tidal#31]
Hi there.
I noticed that something in vim-tidal is working different from "non-vim-tidal".

Normally if I have something like this:
```
p 1 $ s "bd(5,8)"

clutchIn 1 4 $ s "stk(11,16,3)"
```
The `1` would refer to pattern 1, and `4` is the number of cycles for the the transition to happen.
In vim-tidal they are the other way round.

I tried to put somethind like this in Tidal.ghci
`xfadeIn i t = transition tidal (Sound.Tidal.Transition.xfadeIn t) i`
instead of
`xfadeIn t = transition tidal (Sound.Tidal.Transition.xfadeIn t)`
but then the transitions won't work at all.

I really enjoy vim-tidal, b.t.w.

best regards,
Gil

**Comment by munshkr** [comment]
Hi Gil, you're right, it seems the parameters of the transitions functions [were swapped recently](https://github.com/tidalcycles/Tidal/issues/450). I'll update the bootloader script to match Tidal's.

**Comment by munshkr** [comment]
Done at 5371a3d9fce37db7c61cb8d9d1dabcc663b9ed93

Just tested with latest Tidal (1.0.7) and this works OK now (that is, full pattern plays after 4 cycles):
```
clutchIn 1 4 $ s "sn(11,16,3)"
```
Make sure you have latest Tidal, there were some [changes](https://github.com/tidalcycles/Tidal/commit/213c8f5a5f35a921c860d69ed968fa8f48cd333a) in the source code related to `clutchIn` (and `anticipateIn`)

**Comment by gilfuser** [comment]
Hi @munshkr 
It's all fine now. Thank you!
