### ISSUE TITLE
BootTidal.hs

### ISSUE THREAD

**Issue by ovitus** [tidalcycles/vim-tidal#33]
Where am I supposed to place the startup configuration for Tidal?

I tried placing it:
/home/awright/.vim/plugged/vim-tidal

**Comment by munshkr** [comment]
You can store it wherever you want. Just export the variable `TIDAL_BOOT_PATH` in your `.bashrc` or `.profile`, like this:
```
export TIDAL_BOOT_PATH=/home/awright/.vim/plugged/vim-tidal/CustomBootScript.ghci
```

**Comment by munshkr** [comment]
I'll close this for now. Feel free to reopen if you still have issues!
