### ISSUE TITLE
simply not working...

### ISSUE THREAD

**Issue by kflak** [tidalcycles/vim-tidal#34]
Terribly sorry for the lame heading, but I can't get this to work. I am new to Tidal, so I am probably just doing some very basic mistakes here... 
System: Arch Linux (with all the hassle this means in terms of getting Haskell to work in the first place. Succeded with this, though...)
Issue: Ctrl-E is not sending anything to Tidal. The tidalvim script opens up a new tmux session with two panes in it, but without any content. I.e. I only get my standard prompts, and have to open tidal in one and nvim in the other. Running the tidal script in a separate terminal works in interactive mode, I can type out the patterns and it works as expected. I tried different versions as well: opening a tmux instance as adviced in the readme, and running nvim in a separate terminal. No joy. Running nvim and tidal in two separate terminal windows without tmux. Also no joy. Don't really know where to start looking for this...

Another question: is tmux essential to all of this, or is it possible to run this without it? I'd prefer not to use tmux if possible.

**Comment by munshkr** [comment]
Hi @kflak, that's weird. The `tidalvim` script fires up tmux and uses the `send-keys` option for typing "vim" and "tidal" on each pane, like [this](https://github.com/tidalcycles/vim-tidal/blob/6421775142ce2e0f5f47a46e08682d9fcf53d6ad/bin/tidalvim#L20-L21).
The bindings (like Ctrl+E) only work if you edit a file ending with `.tidal` in vim.

There is a PR that adds support for the `terminal` feature in Neovim [here](https://github.com/tidalcycles/vim-tidal/pull/26). I haven't tested it yet, but in the mean time you could try her forked repo. There is also https://github.com/flupe/vim-tidal for Vim.

**Comment by kflak** [comment]
Interesting indeed that it doesn't work. I get a short flash of "Can't find pane 0" before the great big nothingness... The nvim terminal version looks very interesting for my purposes, I am a big fan of [scnvim](https://github.com/davidgranstrom/scnvim) so if I could get this kind of setup up and running, I'd be very happy. Will give it a try!

**Comment by kflak** [comment]
... a few seconds later and I can confirm that @purpleposeidon's fork works like a charm on my system! Very happy not to have to deal with tmux :-)

**Comment by munshkr** [comment]
Great to hear that :) I'll look into merging it
