### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by aleksandryakunichev** [tidalcycles/vim-tidal#35]
Hi! Thanks a lot for this awesome plugin, but I'm struggling with code execution performance :( 

After calling `:TidalSend` it is about 3 seconds before the code actually sends to tmux pane and executes in `ghc`. What can I do about it?

[Here is](https://github.com/aleksandryakunichev/.vimrc/blob/master/init.vim#L112) my config if it can help!

![vim tidal performance issue](https://res.cloudinary.com/canvaskisa/image/upload/v1561116156/vim-tidal_y3e5fi.gif "vim tidal performance issue")
_Do not mind `Failed to send error` — I was lazy to startup SuperCollider :)_

**Comment by munshkr** [comment]
Hi! That's weird... can you try adding `let g:tidal_flash_duration = 1` at the end of your `.vimrc` file? 
Is this neovim?

**Comment by aleksandryakunichev** [comment]
Unfortunately, `let g:tidal_flash_duration = 1` has no effect :(

It is neovim, yes!

**Comment by aleksandryakunichev** [comment]
@munshkr Thanks for help! I've put a reference to a solution [here](https://github.com/jpalardy/vim-slime/issues/204).

**Comment by munshkr** [comment]
Good to know you sorted it out!
