### ISSUE TITLE
can't use more then one block comment

### ISSUE THREAD

**Issue by ovitus** [tidalcycles/vim-tidal#39]
Something like the following will work:
d1 $ striate 5 {-test-} $ struct "1(8,16)" "8s" # comb 0.5

but adding a second block comment breaks things:
d1 $ striate 5 {-test-} $ struct "1(8,16)" "8s" # {-test2-} comb 0.5

Talked about this on talk.lurk.org and there might be an issue here in ftplugin/vim-tidal:
" remove block comments
function! Remove_block_comments(text)
    return substitute(a:text, "{-.*-}", "", "g")
endfunction

**Comment by munshkr** [comment]
Thanks! you know, that "remove comment" functions were copied from vim-slime, but actually I don't think they are really needed, so I've just removed them. Can you pull changes and try again? I think the example now works correctly.

**Comment by ovitus** [comment]
thanks, I updated it before reading your comment as I figured mine was outdated. It's working now!

**Comment by munshkr** [comment]
Awesome :)
