### ISSUE TITLE
Not getting NeoVim Terminal

### ISSUE THREAD

**Issue by gilfuser** [tidalcycles/vim-tidal#41]
Hi!
I really like the idea of getting rid of Tmux. Is one moving part less and frankly it is not necessary.
I just tried to put `let g:tidal_target = "terminal"` in my init.vim file and open `tidalvim`, but I'm still getting Tmux. What am I missing?

In plugged/vim-tidal/bin/tidalvim should I change this?  `VIM=${VIM:-"vim"}`

kind regards,
Gil

**Comment by munshkr** [comment]
Hi! You should just use `nvim` instead of `tidalvim`. Try opening a `.tidal` file in NeoVim, then write something and evaluate it with  <kbd>ctrl</kbd>-<kbd>e</kbd> or <kbd>localleader</kbd>-<kbd>s</kbd>. NeoVim should open a terminal with tidal running there.

**Comment by gilfuser** [comment]
Aha! That's what I was missing!

Thank you!

**Comment by blinry** [comment]
Me too! :) This should probably be clarified in the README.
