### ISSUE TITLE
latest release does not work

### ISSUE THREAD

**Issue by mxmxyz** [tidalcycles/vim-tidal#48]
Downloading the latest release from the master branch and moving it to ~/.tidal doesn't work with the current version of Tidal (ghci complains about a lot of things, such as `d1-d9` not being defined), whereas cloning the current code does.

I think this warrants a new release.

**Comment by gilfuser** [comment]
Hi @mxmxyz.
You should have it in a folder like `~/.vim/plugged/vim-tidal` as in the README. In my case it's in `~/.local/share/nvim/plugged/vim-tidal`.
Using the plugin manager things should be simpler. The command `PlugUpdate` in your vim config file would do it automatically for you.

**Comment by mxmxyz** [comment]
I know, I use plug for this :) but yesterday I was helping someone who doesn't use any plugins, and it didn't feel worth it to install Plug just for it.

So I followed the README, as per line 70:

"If you don't want a plugin manager, you can also download the latest release here and extract the contents on your Vim directory (usually `~/.vim/`)."

While Plug is fine, manual installation (which should still be an option) doesn't, at least in the way it is described in the README. Imo either the README should be updated (by suggesting to `git clone` the repo and `mv` it) or a new release should be made


(ps I only now noticed I made a typo in my first post: i moved the folder to `.vim`, not to `.tidal`!)

**Comment by munshkr** [comment]
Hi @mxmxyz thank you for bringing this up. Yeah, the README suggests using releases, but haven't been keeping it up to date unfortunately. I will create a release now with the latest Tidal bootstrap.
