### ISSUE TITLE
Sound.OSC.FD import error (Tidal 1.7)

### ISSUE THREAD

**Issue by rmassidda** [tidalcycles/vim-tidal#59]
OS: Fedora 33
GHC version: 8.10.4
Cabal version: 3.2.0.0
Tidal version: 1.7

After clean install, running the `tidal` script produces the following error:

```
<no location info>: error:                                                                                
Could not load module ‘Sound.OSC.FD’                                                                  
It is a member of the hidden package ‘hosc-0.18.1’.                                                   
You can run ‘:set -package hosc’ to expose it.                                                        
(Note: this unloads all the modules in the current scope.)
```

**Comment by munshkr** [comment]
Hi. That sounds more like a Tidal problem. You should check out [this forum discussion] for more info and some ways to solve it.

In my case (Ubuntu), I also had the same issue, and solved with by deleting the whole `~/.ghc` directory (where all GHC packages reside) and reinstall Tidal, like this:

```bash
rm -rf ~/.ghc/
cabal v1-update
cabal v1-install tidal
```

If your GHC is old, you may need to use `cabal update`/`cabal install`.

**Comment by rmassidda** [comment]
Actually worked, thanks :)
