### ISSUE TITLE
Latests commits probably broke the plugin on Linux

### ISSUE THREAD

**Issue by tiagohermano** [tidalcycles/vim-tidal#70]
For the purpose of letting you guys know, I updated the plugin and I noticed that PR #68 broke my current installation.

I'm running the plugin on Linux without Tmux. After the update I've got the following error whenever I executed a `TidalSend`:
`zsh:1: file or directory not found: ../bin/tidal`

As you can see I'm also using zsh as my default shell.

After reverting the binary path the plugin got working again.

**Comment by munshkr** [comment]
Oops.. will look into it. Probably the best would be to look for the path of the script file and use a relative path from there, otherwise it would depend on where you start Vim.
