### ISSUE TITLE
Error detected while processing function ... / 

### ISSUE THREAD

**Issue by flechtwerkflechtwerk** [tidalcycles/vim-tidal#71]
Today vim-tidal suddenly stopped working - I get the following error when trying to send a line of code:

Error detected while processing function <SNR>30_TidalSendOp[19]..<SNR>30_TidalSend[5]..<SNR>30_TidalDispatch[2]..<SNR>30_TerminalSend:
line    2:
Can't send data to closed stream

I'm not aware of any changes I made to my system that could have caused this. Yesterday everything was working fine. (Running tidal from terminal works fine too, it's a vim-tidal related error.)

**Comment by munshkr** [comment]
@flechtwerkflechtwerk Could you update the plugin and try again? I've just reverted a recent commit that caused issues.

**Comment by flechtwerkflechtwerk** [comment]
It works again, thank you!
