### ISSUE TITLE
Newline not sent when evaluating a line.

### ISSUE THREAD

**Issue by lazakoa** [tidalcycles/vim-tidal#80]
vim-tidal used to immediately evaluate your code in the repl when you hit ctrl-e, now it sends the code snippet to the prompt but does not send the newline. You have to jump to the repl and click enter to evaluate your code. I don't know if this is an issue with ghci or vim-tidal.

**Comment by mitchmindtree** [comment]
This might be caused by https://github.com/tidalcycles/vim-tidal/commit/1f4d11548c9f25d12ce56015b31b60b264ff226a#r84654919.
